import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { ModuleInfo } from "./scan.js";
import { fmtLoc } from "./scan.js";
import type { Hotspot } from "./churn.js";
import type { EntryPoint } from "./entrypoints.js";

export const PENDING = "_(description pending — fill via AI agent, see SKILL.md)_";
const VERSION = "0.1.0";

interface Existing {
  // `stale` = the stored text came from a stale/placeholder marker, not a fresh
  // agent-authored description. Such entries never render as "fresh" and always
  // stay pending — this is what stops stale markers from nesting on every regen.
  descriptions: Map<string, { hash: string; text: string; stale: boolean }>;
  sections: Map<string, string>;
}

const STALE_PREFIX = '_(stale — module changed; previous: "';
const STALE_SUFFIX = '")_';

/** Peel any (possibly nested) stale wrappers to recover the innermost description. */
function unwrapStale(text: string): { text: string; stale: boolean } {
  let t = text;
  let stale = false;
  while (t.startsWith(STALE_PREFIX) && t.endsWith(STALE_SUFFIX)) {
    t = t.slice(STALE_PREFIX.length, t.length - STALE_SUFFIX.length);
    stale = true;
  }
  return { text: t, stale };
}

/** Parse an existing MAP.md to preserve agent-written content. */
export function parseExisting(root: string): Existing {
  const result: Existing = { descriptions: new Map(), sections: new Map() };
  const mapPath = join(root, "MAP.md");
  if (!existsSync(mapPath)) return result;

  const content = readFileSync(mapPath, "utf8");

  const modRe =
    /<!-- cartographer:module path="([^"]+)" hash="([^"]+)" -->\s*\n### [^\n]*\n([\s\S]*?)(?=\n<!-- cartographer:|\n## |$)/g;
  for (const m of content.matchAll(modRe)) {
    const body = m[3].trim();
    // description = first non-empty line that isn't the "Depends on:" line
    const desc = body
      .split("\n")
      .map((l) => l.trim())
      .find((l) => l && !l.startsWith("Depends on:"));
    if (desc && desc !== PENDING) {
      const { text, stale } = unwrapStale(desc);
      result.descriptions.set(m[1], { hash: m[2], text, stale });
    }
  }

  const secRe =
    /<!-- cartographer:section id="([^"]+)" -->\s*\n([\s\S]*?)(?=\n<!-- cartographer:|\n## |$)/g;
  for (const m of content.matchAll(secRe)) {
    const body = m[2].trim();
    if (body && !body.startsWith("_(pending")) result.sections.set(m[1], body);
  }
  return result;
}

export function emitMap(opts: {
  modules: ModuleInfo[];
  deps: Map<string, Set<string>>;
  hotspots: Hotspot[];
  entryPoints: EntryPoint[];
  existing: Existing;
}): { markdown: string; pending: string[] } {
  const { modules, deps, hotspots, entryPoints, existing } = opts;
  const pending: string[] = [];
  const lines: string[] = [];

  lines.push("# Codebase Map", "");
  lines.push(
    `<!-- cartographer:meta generated="${new Date().toISOString()}" version="${VERSION}" -->`,
  );
  lines.push(
    "> Generated by [codebase-cartographer](https://www.npmjs.com/package/codebase-cartographer).",
    "> Agents: read this file BEFORE exploring the repo. Refresh with `npx codebase-cartographer generate`.",
    "",
  );

  // Entry points
  lines.push("## Entry points", "");
  if (entryPoints.length) {
    lines.push("| Entry | Path / command | Kind |", "|---|---|---|");
    for (const e of entryPoints)
      lines.push(`| ${e.name} | \`${e.path.replace(/\|/g, "\\|")}\` | ${e.kind} |`);
  } else {
    lines.push("_None detected._");
  }
  lines.push("");

  // Modules
  lines.push("## Modules", "");
  for (const m of modules) {
    const prev = existing.descriptions.get(m.path);
    // A description is "fresh" only if the agent authored it (not a stale
    // placeholder) AND the module hasn't changed since.
    const authored = prev && !prev.stale;
    const fresh = authored && prev.hash === m.hash ? prev.text : null;

    lines.push(`<!-- cartographer:module path="${m.path}" hash="${m.hash}" -->`);
    lines.push(`### \`${m.path}\` · ${m.files.length} files · ${fmtLoc(m.loc)}`);

    if (fresh) {
      lines.push(fresh);
    } else {
      // prev.text is already the unwrapped innermost description → no nesting.
      if (prev && prev.text) {
        lines.push(`_(stale — module changed; previous: "${prev.text}")_`);
      } else {
        lines.push(PENDING);
      }
      pending.push(m.path);
    }

    const to = deps.get(m.path);
    if (to?.size)
      lines.push("", `Depends on: ${[...to].sort().map((d) => `\`${d}\``).join(", ")}`);
    lines.push("");
  }

  // Dependency graph (text edges — renders everywhere, no mermaid required)
  lines.push("## Dependency graph", "", "```");
  let edgeCount = 0;
  for (const [from, tos] of [...deps.entries()].sort()) {
    for (const to of [...tos].sort()) {
      lines.push(`${from} ──▶ ${to}`);
      edgeCount++;
    }
  }
  if (!edgeCount) lines.push("(no cross-module imports detected)");
  lines.push("```", "");

  // Hotspots
  lines.push("## Hotspots (last 90 days)", "");
  if (hotspots.length) {
    lines.push("| Module | Commits touching | Top file |", "|---|---|---|");
    for (const h of hotspots)
      lines.push(`| \`${h.module}\` | ${h.commits} | \`${h.topFile}\` |`);
  } else {
    lines.push("_No git history available (not a git repo, or no recent commits)._");
  }
  lines.push("");

  // Agent-owned sections
  for (const [id, title, hint] of [
    ["conventions", "Conventions", "naming, error handling, test layout, patterns you observed"],
    ["architecture", "Architecture notes", "3–5 bullets on layers, data flow, key decisions"],
  ] as const) {
    lines.push(`## ${title}`, "");
    lines.push(`<!-- cartographer:section id="${id}" -->`);
    const prev = existing.sections.get(id);
    if (prev) lines.push(prev);
    else {
      lines.push(`_(pending — agent: ${hint})_`);
      pending.push(`section:${id}`);
    }
    lines.push("");
  }

  return { markdown: lines.join("\n"), pending };
}
